bundler_args: --without development
gemfile:
  - Gemfile
language: ruby
before_install:
  - gem install bundler 
  - gem update bundler
rvm:
  - 2.3.0
  - 2.5.8
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
